/*
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.example.youtube.api;

import com.example.youtube.api.model.Video;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

public interface SearchApi extends BaseApi {

  @RequestMapping(
    value = "/v1/search",
    produces = {"application/json"},
    method = RequestMethod.GET
  )
  default ResponseEntity<List<Video>> searchVideosResource(
      @RequestParam(value = "keyword", required = true) String keyword) {
    return this.searchVideos(keyword);
  }

  ResponseEntity<List<Video>> searchVideos(String keyword);

}
