/*
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.example.youtube.api;

import com.example.youtube.api.model.Video;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

public interface VideosApi extends BaseApi {

  @RequestMapping(
    value = "/v1/videos",
    produces = {"application/json"},
    method = RequestMethod.GET
  )
  default ResponseEntity<List<Video>> getVideosResource() {
    return this.getVideos();
  }

  ResponseEntity<List<Video>> getVideos();


}
