/*
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.example.youtube.api.model;

import java.io.Serializable;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;


public class Video implements Serializable {

  private static final long serialVersionUID = 1L;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("publishingDate")
  private String publishingDate = null;

  @JsonProperty("thumbnailURI")
  private String thumbnailURI = null;


  public String getId() {
    return id;
  }
  public Video id(String id) {
  this.id = id;
  return this;
  }
  public void setId(String id) {
    this.id = id;
  }

  public String getTitle() {
    return title;
  }
  public Video title(String title) {
  this.title = title;
  return this;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  public String getDescription() {
    return description;
  }
  public Video description(String description) {
  this.description = description;
  return this;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  public String getPublishingDate() {
    return publishingDate;
  }
  public Video publishingDate(String publishingDate) {
  this.publishingDate = publishingDate;
  return this;
  }
  public void setPublishingDate(String publishingDate) {
    this.publishingDate = publishingDate;
  }

  public String getThumbnailURI() {
    return thumbnailURI;
  }
  public Video thumbnailURI(String thumbnailURI) {
  this.thumbnailURI = thumbnailURI;
  return this;
  }
  public void setThumbnailURI(String thumbnailURI) {
    this.thumbnailURI = thumbnailURI;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Video video = (Video) o;
    return Objects.equals(this.id, video.id) &&
      Objects.equals(this.title, video.title) &&
      Objects.equals(this.description, video.description) &&
      Objects.equals(this.publishingDate, video.publishingDate) &&
      Objects.equals(this.thumbnailURI, video.thumbnailURI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, description, publishingDate, thumbnailURI);
  }

  @Override
  public String toString() {
    return "class Video {\n"
      + "    id: " + toIndentedString(id) + "\n"
      + "    title: " + toIndentedString(title) + "\n"
      + "    description: " + toIndentedString(description) + "\n"
      + "    publishingDate: " + toIndentedString(publishingDate) + "\n"
      + "    thumbnailURI: " + toIndentedString(thumbnailURI) + "\n"
      + "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

